version: "3.8"

services:
  front:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
    ports:
      - "5173:5173"
    # volumes:
    #   - ./front:/app
    working_dir: /app

  back:
    build:
      context: .
      dockerfile: docker/Dockerfile.back
    ports:
      - "8000:80"
    volumes:
      - ./back:/var/www/html
    working_dir: /var/www/html

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: genshin
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
